name: Auto Commit and Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # Запуск раз в 5 минут

jobs:
  commit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Используем токен из GitHub Secrets
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Настройка Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Проверка remote URL
        run: git remote -v

      - name: Коммит и пуш изменений
        run: |
          git add .
          git commit -m "Автообновление файлов" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/MaxKorolev-ep/dkp_bot.git main
